cacheDuration: 60000000000
dbName: hatchet
host: postgres
logger:
  format: console
  level: error
maxConns: 20
maxQueueConns: 50
minConns: 10
minQueueConns: 10
password: mypassword
port: 5432
seed:
  adminEmail: admin@example.com
  adminName: Admin
  adminPassword: Admin123!!
  defaultTenantId: 707d0855-80ab-4e1f-a156-f1c4546cbf52
  defaultTenantName: Default
  defaultTenantSlug: default
sslMode: disable
username: myuser
